### ISSUE TITLE
How can I resize waveform for 30 seconds play? Please, HELP!

### ISSUE THREAD

**Issue by samkgaibek** [google/ringdroid#2]
Guys, how can i resize waveform so that the width of the screen of the device was for example 30 seconds. So that u can't use Marker and define the StartPos and EndPos with the width of screen. Please, HELP!

Here is more clear.
![untitled](https://cloud.githubusercontent.com/assets/4330131/7657035/6a1f0fee-fb37-11e4-8a14-9edc04a22c16.png)
Thanks!!!

**Comment by samkgaibek** [comment]
SOLVED!!!

**Comment by nzala** [comment]
Ringdroid waveform in full width according to width of mobile screen

**Comment by nzala** [comment]
Ringdroid waveform in full width according to width of mobile screen

@theaibek

**Comment by heyaibek** [comment]
@nzala, i've closed issue, but thank you for information! =)
